# Generated by Django 3.0.7 on 2020-06-26 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_user_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Created by '),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_user_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Updated by '),
        ),
    ]
