# Generated by Django 3.0.7 on 2020-07-29 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('person', '0003_auto_20200724_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='persontype',
            name='block_discount',
            field=models.BooleanField(default=True, verbose_name='Block Discount'),
        ),
        migrations.AddField(
            model_name='persontype',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='person.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address Number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fantasy_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fantasy Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, max_length=200, upload_to='company/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='Neighborhood'),
        ),
        migrations.AlterField(
            model_name='company',
            name='number_state',
            field=models.CharField(blank=True, max_length=30, verbose_name='Number State'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_1',
            field=models.CharField(blank=True, max_length=20, verbose_name='Main Phone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Secundary Phone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='company',
            name='user_created',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_user_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='company',
            name='user_updated',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_user_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='company',
            name='zip_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='department',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='department',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='department',
            name='user_created',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_user_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='department',
            name='user_updated',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_user_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='persontype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='persontype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='persontype',
            name='max_discount',
            field=models.PositiveIntegerField(verbose_name='Discount Max'),
        ),
        migrations.AlterField(
            model_name='persontype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='persontype',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='persontype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='persontype',
            name='user_created',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_type_user_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='persontype',
            name='user_updated',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_type_user_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.DeleteModel(
            name='MaxDiscount',
        ),
    ]
