# Generated by Django 3.0.7 on 2020-08-02 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='department',
        ),
        migrations.RemoveField(
            model_name='person',
            name='person_type',
        ),
        migrations.DeleteModel(
            name='PersonType',
        ),
    ]
