# Generated by Django 3.0.7 on 2020-08-04 00:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('person', '0007_situation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Situation',
            new_name='Position',
        ),
    ]
