# Generated by Django 3.0.7 on 2020-08-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_auto_20200803_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='person',
            name='drivers_license_validate',
            field=models.DateField(blank=True, max_length=20, null=True, verbose_name='Drivers License - Validate'),
        ),
    ]
