# Generated by Django 3.0.7 on 2020-08-29 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('person', '0009_auto_20200822_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.Person', verbose_name='person')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.Position', verbose_name='position')),
                ('user_created', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_position_user_created_id', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('user_updated', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_position_user_updated_id', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'PersonPosition',
                'verbose_name_plural': 'PersonPositions',
                'ordering': ['person'],
            },
        ),
        migrations.AddField(
            model_name='position',
            name='members',
            field=models.ManyToManyField(through='person.PersonPosition', to='person.Person'),
        ),
    ]
