BBBB BBBBBB
BBBB BBBBBBBBBBBBBBBBB
XXXXXXXXX XXXXX
XXXXXX
XXXXXX
   XXXX XXXXXXXX XXXX XXXX XXX
    BBBBBBB BBBBBBBBBBBBBBBBB

    XXXXXXX BBBBB BBBBB BBBBBBBB BBBBB XXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBB    

    XXXX XXX XX XXXXXXXX XXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBB   
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
    XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX
    XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXX X XXX XXXX
  XXXXXX
  XXXX XXXXXXXXXXXX XXX
  XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX X XXXXXXXXXX

      XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBXX
        BBBBBBBBBB
        FFFFFF        
        XXXX XXXXXXXXXXXX          
          XXXX XXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXX XXX
        XXXXXX
      XXXXXXX

      XX XXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBXXXXXXXXX XXXXX XXXXXXXXX
      XXXX      
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXX
  XXXXXX
XXXXXX
XXXX XXXXXXXXXXX XXX

 BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
XXXXXXX
XXXXXXX
