BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXX XXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXX XXXXXXXXX

      XXXXX XXXXXXXXXXXXX X
        BBBBBBBBBB
        FFFFFF        
        XXXX XXXXXXXXXXXX          
          XXXX XXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXX XXX
        XXXXXX
      XXXXXXX
          
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXX
XXXXXX

BBBBBBBB BBBBBBB