BBBB BBBBBB
BBBB BBBBBBBBBBBBBBBBB
XXXXXXXXX XXXXX
XXXXXX
XXXXXX
   XXXX XXXXXXXX XXXX XXXX XXX
    BBBBBBB BBBBBBBBBBBBBBBBB

    XXXXXXX BBBBB BBBBB BBBBBBBB BBBBB XXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBB    

    XXXX XXX XX XXXXXXXX XXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBB   
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
    XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX
    XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXX X XXX XXXX
  XXXXXX
  XXXX XXXXXXXXXXXX XXX
  XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXX XXXX XX XXXX XXXXX XXXXXXXXXXXXXX    

     XX XXXXXXXXXXX XXXXXX
        XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXBBB BBBBBBBXXXXXXXXXXX
      XXXX         
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXX
  XXXXXX
XXXXXX
XXXX XXXXXXXXXXX XXX

 BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
XXXXXXX
XXXXXXX
